# vim:set ft=tmux:
# Code 2026 - Application Module

set -ogq @code-2026_application_icon " "
set -ogqF @code-2026_application_color "#{@thm_annotation}"
set -ogq @code-2026_application_text " #{pane_current_command}"
